import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Notes.module.scss";

export default function Notes() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.notes}>
        <Link href="/">Back</Link>
        <h1>Notes</h1>
        <ul>
          <li>
            <h2>Quarry</h2>
            <p>Lorem ipsum</p>
          </li>
        </ul>
      </main>
    </>
  );
}
